// Rate Limit
pub const RATE_LIMIT_PREFIX: &str = "rate_limit";

// pub const BROADCAST_HOST_RECONNECTION_TIMEOUT_SECONDS: u64 = 800;
// pub const BROADCAST_PARTICIPANT_RECONNECTION_TIMEOUT_SECONDS: u64 = 800;
