pub const BLOCKLIST_PREFIX: &str = "AUTH.BLOCKLIST";
pub const RD_VERIFY_EMAIL_OTP_PREFIX: &str = "AUTH.OTP.VERIFY_EMAIL";
pub const RD_VERIFY_EMAIL_OTP_TTL_SECS: i64 = 900;

pub const RD_RESET_PASSWORD_OTP_PREFIX: &str = "AUTH.OTP.RESET_PASSWORD";
pub const RD_RESET_PASSWORD_OTP_TTL_SECS: i64 = 900;

pub const RD_RESEND_RATE_LIMIT_PREFIX: &str = "AUTH.OTP.RESEND_RATE_LIMIT";
pub const RD_RESEND_RATE_LIMIT_TTL_SECS: i64 = 60;

pub const RD_OAUTH_STATE_PREFIX: &str = "AUTH.OAUTH2";
pub const RD_OAUTH_STATE_TTL_SECS: i64 = 300;
